name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: cypress-io/github-action@v2.2.7
        with:
          build: npm run build
          start: npm start
