name: Execute Cypress Tests
on:
  push:

jobs:
  cypress-Tests:
    name: Run on Chrome 97
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.2-chrome97-ff96
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm ci

      - name: Install cypress and verify
        run: npm install

      - name: Run Cypress Tests
        run: npm run test
        continue-on-error: false
