name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: cypress-io/github-action@v2.2.7
        with:
          run: npm run build
          run: npm run test

      - name: Upload screenshots
        uses: actions/upload-artifact@latest
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
