name: Execute Cypress Tests
on:
  push:

jobs:
  cypress-Tests:
    name: Run on Chrome 97
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.2-chrome97-ff96
    
    steps:
      -uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
        npm ci
        $(npm bin)/cypress verify

      - name: Run Cypress Tests
        run: npm run test
        continue-on-error: false

      - name: Copy text execution videos and screenshots
        run: |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshot public/screenshots