name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Tests
        run: |
          npm cy:run
        uses: cypress-io/github-action@v2.9.2
