name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: macoos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Tests
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npx cypress run
