name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm setup
        # You may pin to the exact commit or the version.
        # uses: ng-easy/npm-setup@e5cc43439b1b38d58809e979c44bc442e2a89ac5
        uses: ng-easy/npm-setup@v1.7.2
        with:
          # Caches NX local execution cache instead of relying on NX Cloud, this param is the key to uniquely identify a job that runs a NX script.
          nx-key: # optional
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npm run build
          start: npm start
